
version: 2

models:
  - name: raw_manual_vienti
    description: "A starter dbt model"
    columns:
      - name: tili
        tests:
          - not_null

  - name: raw_tiliote
    description: "A starter dbt model"
    columns:
      - name: jarjno
        description: "Row number"
        tests:
          - unique
          - not_null
